server:
  port: 8080
  contextPath: /AssetManager

logging:
  level:
    org.springframework.web: ERROR
    com.assetmanager: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
#  file: /var/log/application.log

datasource:
  url: jdbc:hsqldb:mem:assetdb
  driverClassName: org.hsqldb.jdbc.JDBCDriver
  user: SA
  password: